In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [6]:
a2 = np.array([[1,2],[3,4]])
a2

array([[1, 2],
       [3, 4]])

In [7]:
a3=np.array([1,2,3,4,5,6])
a3_reshaped=a3.reshape(2,3)
a3_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
one_matrix=np.ones((2,2))
one_matrix

array([[1., 1.],
       [1., 1.]])

In [9]:
int_matrix=np.ones((2,2),dtype='int')
int_matrix

array([[1, 1],
       [1, 1]])

In [11]:
zero_matrix=np.zeros((2,2))
zero_matrix

array([[0., 0.],
       [0., 0.]])

In [12]:
np.full((2,2),5)


array([[5, 5],
       [5, 5]])

In [13]:
np.ones((2,8))


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
np.random.randint(0,100,(3,3))

array([[29, 95, 94],
       [19, 39, 75],
       [52, 61, 86]])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
l1=[1,2,3]
l2=[1,2,3]
a1=np.array(l1)
a2=np.array(l2)
a1+a2

array([2, 4, 6])

In [23]:
a1*a2

array([1, 4, 9])

In [25]:
import pandas as pd


In [27]:
s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [28]:
s.iloc[0]

np.int64(1)

In [29]:
s1=pd.Series([4,5,6,7],index=['a','b','c','d'])
s1

a    4
b    5
c    6
d    7
dtype: int64

In [33]:
s1.iloc[0:2]

a    4
b    5
dtype: int64

In [31]:
s1.loc['a']

np.int64(4)

In [35]:
s1+2

a    6
b    7
c    8
d    9
dtype: int64

In [37]:
ms=pd.Series([1,2,3,4])
ms*10

0    10
1    20
2    30
3    40
dtype: int64

In [38]:
df=pd.DataFrame({'Name':['sankalp','nishant','samay','yogesh'],'Age':[19,20,21,22]})
df

Name  Age
0  sankalp   19
1  nishant   20
2    samay   21
3   yogesh   22

In [42]:
df.Name

0    sankalp
1    nishant
2      samay
3     yogesh
Name: Name, dtype: object

In [43]:
df['Name']

0    sankalp
1    nishant
2      samay
3     yogesh
Name: Name, dtype: object

In [45]:
df[['Name','Age']]

Name  Age
0  sankalp   19
1  nishant   20
2    samay   21
3   yogesh   22

In [47]:
df.loc[df['Age']>=20,['Name','Age']]

Name  Age
1  nishant   20
2    samay   21
3   yogesh   22

In [41]:
data=[['aditya','delhi'],['rohan','gurgaon'],['vishal','faridabad'],['raghav','haryana']]
df1=pd.DataFrame(data,columns=['Name','Place'])
df1

Name      Place
0  aditya      delhi
1   rohan    gurgaon
2  vishal  faridabad
3  raghav    haryana